import { writeTextFile } from "../utils/fs.ts";

export function writeWithPreamble(filePath: string, fileContent: string) {
  return writeTextFile(
    filePath,
    "# THIS FILE IS AUTOGENERATED. DO NOT EDIT IT BY HAND.\n" + fileContent,
  );
}
