[default]
locale = "en-us"

# https://github.com/catppuccin/userstyles/blob/main/styles/chess.com/scripts/generate.py#L2
[type.py.extend-identifiers]
Flavour = "Flavour"
flavour = "flavour"
flavours = "flavours"

[files]
extend-exclude = ["styles/*/*.user.css"]
