[default]
locale = "en-us"

# maintainer names
[default.extend-words]
Ren = "Ren"

# catppuccin python spelling
[type.py.extend-identifiers]
Flavour = "Flavour"
flavour = "flavour"
flavours = "flavours"

[type.css]
extend-ignore-re = [
  # css classnames
  '\.[\w\d\-_]+(\[[\w\d\-_]+\])?',
]
