[default]
locale = "en-us"

# maintainer names
[default.extend-words]
Ren = "Ren"

# catppuccin python spelling
[type.py.extend-identifiers]
Flavour = "Flavour"

[type.css]
extend-ignore-re = [
  # generated classnames from css modules
  '_[\w\d]+',
]
