[default]
locale = "en-us"

# maintainer names
[default.extend-words]
Ren = "Ren"               # maintainer
unavilable = "unavilable" # needed for deepl
bloks = "bloks"           # needed for instagram

# catppuccin python spelling
[type.py.extend-identifiers]
Flavour = "Flavour"
flavour = "flavour"
flavours = "flavours"

[files]
extend-exclude = ["scripts/dist/import.json"]

[type.css]
extend-ignore-re = [
  # css classnames
  '[\.#][\w\d\-_]+(\[[\w\d\-_]+\])?',
]
