blank_issues_enabled: false
contact_links:
  - name: Theme Request
    url: https://github.com/catppuccin/catppuccin/discussions/new?category=port-requests
    about: Request a website to be themed here!
  - name: Theme Review
    url: https://github.com/catppuccin/userstyles/compare
    about: Already made a theme? Raise a Pull Request here!
  - name: Community Discord
    url: https://discord.com/servers/catppuccin-907385605422448742
    about: Ask questions and chat to other community members!