name: Meta Issue
description: Report your issues with the repository here!
labels: [meta]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue outlining your problem?
      description: Please search to see if an issue already exists for your problem.
      options:
        - label: I have searched the existing issues and they do not solve my problem.
          required: true
  - type: textarea
    attributes:
      label: Describe your issue.
      description: "Note that issues relating to individual themes should be raised via [Userstyle Issue](https://github.com/catppuccin/userstyles/issues/new?assignees=&labels=&template=userstyle.yml)."
    validations:
      required: true
