name: Meta Issue
description: Report your issues with the repository here!
labels: [meta]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue outlining your problem?
      options:
        - label: I have searched the existing issues and they do not solve my problem.
          required: true
  - type: textarea
    attributes:
      label: Describe your issue.
      description: "Does your issue only affect one userstyle? Open an [Userstyle Issue](https://github.com/catppuccin/userstyles/issues/new?assignees=&labels=&template=userstyle.yml) instead."
    validations:
      required: true
