[book]
title = "catppucin/userstyles"
authors = ["uncenter"]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "mocha"
preferred-dark-theme = "mocha"
additional-css = ["./theme/catppuccin.css"]
no-section-label = true
git-repository-url = "https://github.com/catppuccin/userstyles"
git-repository-icon = "fa-github"
cname = "userstyles.catppuccin.com"

[preprocessor.alerts]
