[book]
title = "catppuccin/userstyles"
authors = ["uncenter"]
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-alerts.css"]
no-section-label = true
git-repository-url = "https://github.com/catppuccin/userstyles"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/catppuccin/userstyles/edit/main/docs/{path}"
cname = "userstyles.catppuccin.com"
[output.html.print]
enable = false

[preprocessor.alerts]
