name: Build Stylus Export

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore: ["docs/**"]

jobs:
  build:
    if: github.repository == 'catppuccin/userstyles'
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.USERSTYLES_TOKEN }}

      - name: Setup Deno
        uses: nekowinston/setup-deno@a790e9ad1e6b1c727a4ea621a8a8219b1f2c373d # main
        with:
          deno-version: v2.3.5

      - name: Generate Stylus import
        run: deno task ci:stylus-import

      - name: Upload release artifact
        run: gh release upload --clobber all-userstyles-export ./dist/import.json
        env:
          GH_TOKEN: ${{ github.token }}
