name: Import File Generator

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1 # At 00:00 on Monday

env:
  HAS_USERSTYLES_TOKEN: ${{ secrets.USERSTYLES_TOKEN != '' }}

jobs:
  generate-health-files:
    name: Generate health files
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple

      - uses: actions/checkout@v4
        if: env.HAS_USERSTYLES_TOKEN && ${{ steps.release.outputs.release_created }}
        with:
          token: ${{ secrets.USERSTYLES_TOKEN }}
          ref: ${{ github.ref }}
      - uses: actions/checkout@v4
        if: env.HAS_USERSTYLES_TOKEN == 'false' && ${{ steps.release.outputs.release_created }}
        with:
          ref: ${{ github.ref }}

      - name: Setup Deno
        if: ${{ steps.release.outputs.release_created }}
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v1.x

      - name: Generate import file
        if: ${{ steps.release.outputs.release_created }}
        run: deno task ci:generate-import

      - name: Upload Release Artifacts
        if: ${{ github.repository == 'catppuccin/userstyles' && github.ref == 'refs/heads/main' && env.HAS_USERSTYLES_TOKEN }} && ${{ steps.release.outputs.release_created }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./dist
