name: Labeler
on:
  workflow_run:
    workflows: ["Generate"]
    types:
      - completed

jobs:
  auto-label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/labeler@v4.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
