name: Labeler
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/labeler@v4.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
