name: Lint & Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ["docs/**"]
  push:
    branches: [main]
    paths-ignore: ["docs/**"]

jobs:
  lint:
    name: Lint Userstyles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run Lint
        run: deno task lint

  build:
    name: Generate Stylus Export
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ github.repository == 'catppuccin/userstyles' && github.ref == 'refs/heads/main' }}
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.USERSTYLES_TOKEN }}
          ref: ${{ github.ref }}

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v1.x

      - name: Generate import file
        run: deno task ci:generate-import

      - name: Upload Release Artifacts
        run: gh release upload --clobber all-userstyles-export ./dist/import.json
        env:
          GH_TOKEN: ${{ github.token }}
