name: Lint & Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

env:
  HAS_USERSTYLES_TOKEN: ${{ secrets.USERSTYLES_TOKEN != '' }}

jobs:
  lint:
    name: Lint Userstyles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run Lint
        run: deno task lint

  build:
    name: Generate Stylus Export
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        if: env.HAS_USERSTYLES_TOKEN
        with:
          token: ${{ secrets.USERSTYLES_TOKEN }}
          ref: ${{ github.ref }}
      - uses: actions/checkout@v4
        if: env.HAS_USERSTYLES_TOKEN == 'false'
        with:
          ref: ${{ github.ref }}

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v1.x

      - name: Generate import file
        run: deno task ci:generate-import

      - name: Upload Release Artifacts
        if: ${{ github.repository == 'catppuccin/userstyles' && github.ref == 'refs/heads/main' && env.HAS_USERSTYLES_TOKEN }}
        run: gh release upload --clobber import-styles ./dist
