name: Pull Request Labeler

on:
  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '(tree-wide)') && !contains(github.event.pull_request.title, '(treewide)') }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Add pull request labels
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
        with:
          configuration-path: .github/pr-labeler.yml
          sync-labels: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
