name: Generate READMEs

on:
  push:
    paths:
      - "src/generate/**"
  pull_request:
    paths:
      - "src/generate/**"
  workflow_dispatch:

env:
  DENO_DIR: deno_cache

jobs:
  readme:
    runs-on: ubuntu-latest
    name: Re-generate README sections

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('src/generate/deno.lock') }}
          path: ${{ env.DENO_DIR }}
      - name: Update READMEs
        working-directory: src/generate
        run: ./main.ts
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        # skip pushing on forks
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          commit_message: "chore: re-generate README sections"
          branch: ${{ github.head_ref }}
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
