name: Sync Labels

on:
  push:
    branches: [main]

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: r7kamura/github-label-sync-action@v0
        with:
          allow_added_labels: "true"
