name: Update Files

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  HAS_USERSTYLES_TOKEN: ${{ secrets.USERSTYLES_TOKEN != '' }}

jobs:
  update-files:
    name: Update files
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        if: env.HAS_USERSTYLES_TOKEN
        with:
          token: ${{ secrets.USERSTYLES_TOKEN }}
          ref: ${{ github.ref }}
      - uses: actions/checkout@v4
        if: env.HAS_USERSTYLES_TOKEN == 'false'
        with:
          ref: ${{ github.ref }}

      - name: Setup Deno
        uses: nekowinston/setup-deno@main
        with:
          deno-version: v1.x

      - name: Generate health files
        run: deno task ci:generate

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.repository == 'catppuccin/userstyles' && github.ref == 'refs/heads/main' && env.HAS_USERSTYLES_TOKEN }}
        with:
          commit_message: "chore: generate health files"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.ref }}

      - name: Format userstyles
        run: npx prettier --write .

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.repository == 'catppuccin/userstyles' && github.ref == 'refs/heads/main' && env.HAS_USERSTYLES_TOKEN }}
        with:
          commit_message: "style: format code with prettier"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.ref }}
